before:
  hooks:
    - go mod tidy
    - ./script/add-acoustid-key
builds:
-
  env:
    - CGO_ENABLED=1
  goos:
    - linux
  goarch:
    - amd64
  hooks:
    post: git checkout internal/acoustid/key.go
archives:
-
  format: gz
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
